M48
; DRILL file {KiCad 7.0.2} date Sat Aug  5 13:01:55 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-05T13:01:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X3.3465Y-2.0874
X3.3465Y-4.0874
X6.1024Y-2.0874
X6.1024Y-4.0874
T0
M30
